[project]
name = "point-operations-training"
version = "0.1.0"
description = "Fun project to help kids to learn multiplication"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.10.0",
    "numpy>=2.2.2",
    "textual>=1.0.0",
    "textual-plotext>=1.0.1",
]
