from typing import Protocol

from point_operations_training.model.model import Model
from point_operations_training.presenter.modus import Modus
from point_operations_training.view.view_protocol import ViewProtocol


class PresenterProtocol(Protocol):

    @property
    def num_assignments(self) -> int: ...

    @property
    def num_training(self) -> int: ...

    @property
    def view(self) -> ViewProtocol: ...

    @property
    def model(self) -> Model: ...

    @property
    def modus(self) -> Modus: ...

    @modus.setter
    def modus(self, value: Modus) -> None: ...

    @property
    def user_name(self) -> str: ...

    @user_name.setter
    def user_name(self, name: str) -> None: ...

    @property
    def users(self) -> list[str]: ...

    def switch_to_create_user_state(self) -> None: ...
    def switch_to_welcome_state(self) -> None: ...
    def switch_to_select_user_state(self) -> None: ...
    def switch_to_select_modus_state(self) -> None: ...
    def switch_to_assignment_state(self) -> None: ...
    def switch_to_training_state(self) -> None: ...
    def switch_to_result_state(self) -> None: ...
    def switch_to_stats_state(self) -> None: ...
