from typing import Protocol

from point_operations_training.model.assignment import AssignmentFactory
from point_operations_training.model.session import Session
from point_operations_training.presenter.state import State
from point_operations_training.view.view import UserView


class PresenterProtocol(Protocol):

    @property
    def num_assignments(self) -> int: ...

    @property
    def num_training(self) -> int: ...

    @property
    def session(self) -> Session: ...

    @property
    def state(self) -> State: ...

    @state.setter
    def state(self, new_state: State) -> None: ...

    @property
    def view(self) -> UserView: ...

    @property
    def modus(self) -> AssignmentFactory: ...

    @modus.setter
    def modus(self, value: AssignmentFactory) -> None: ...

    @property
    def user_name(self) -> str: ...

    @user_name.setter
    def user_name(self, name: str) -> None: ...

    @property
    def users(self) -> list[str]: ...

    def commit_assignment(self) -> None: ...
    def switch_to_create_user_state(self) -> None: ...
    def switch_to_welcome_state(self) -> None: ...
    def switch_to_select_user_state(self) -> None: ...
    def switch_to_select_modus_state(self) -> None: ...
    def switch_to_assignment_state(self) -> None: ...
    def switch_to_training_state(self) -> None: ...
    def switch_to_result_state(self) -> None: ...
