from typing import Protocol


class State(Protocol):
    def select_user(self) -> None: ...
    def select_modi_operandi(self) -> None: ...
    def start_assignments(self) -> None: ...
    def create_user(self) -> None: ...
    def home(self) -> None: ...
