- name: Setup Radar Demo
  hosts: dev
  roles:
    - role: distupgrade
    - role: bash
    - role: direnv
    - role: python
    - role: poetry
    - role: launcher
  tasks:
    - name: Install System Packages
      become: true
      ansible.builtin.package:
        name:
          - curl
          - htop
          - git
          - vim
        state: present
