from typing import Protocol

from point_operations_training.model.result import ResultCollectionProtocol
from point_operations_training.presenter.modus import Modus


class Model(Protocol):
    @property
    def users(self) -> list[str]: ...
    @property
    def user(self) -> str: ...
    @user.setter
    def user(self, user_name: str) -> None: ...
    @property
    def modus(self) -> Modus: ...
    @modus.setter
    def modus(self, modus: Modus) -> None: ...
    def start_session(self) -> None: ...
    def get_new_assignment(self) -> str: ...
    def get_next_train_assignment(self) -> str: ...
    def commit_assignment(self) -> None: ...
    def get_solved_progress(self) -> tuple[int, int]:
        """Returns a tuple with the number of solved assignments and total assignments to be solved."""
        ...

    def get_training_progress(self) -> tuple[int, int]:
        """Returns a tuple with the number of solved training assignments and total training assignments to be
        solved."""
        ...

    def save_session(self) -> None: ...
    def session_min(self) -> float: ...
    def session_max(self) -> float: ...
    def session_avg(self) -> float: ...
    def get_results(self) -> ResultCollectionProtocol: ...
